// Injetado no <head> do /admin-core-sys: adiciona "Usuários" no menu lateral e mostra a
// gestão (/api/admin/ui) INLINE na área de conteúdo (como as outras seções). Ao clicar, a
// URL vira /admin-core-sys/users; clicar em outra seção fecha. JS sem backticks/${}.
export const MENU_INJECT = `<script>(function(){
var URLP='/admin-core-sys/users';
function sbRight(){try{var a=document.querySelector('a[href="/admin-core-sys"]')||document.querySelector('a[href^="/admin-core-sys"]');if(!a)return 240;var sb=a;while(sb.parentElement&&sb.parentElement.querySelectorAll('a[href^="/admin-core-sys"]').length>=3)sb=sb.parentElement;var r=Math.round(sb.getBoundingClientRect().right);return (r>80&&r<520)?r:240}catch(e){return 240}}
function highlight(on){var it=document.getElementById('mi-usuarios');if(!it)return;if(on){it.style.background='oklch(0.969 0.015 12.422)';it.style.color='oklch(0.514 0.222 16.935)';it.style.borderRadius='12px'}else{it.style.background='';it.style.color='';it.style.borderRadius=''}}
function showU(push){var fr=document.getElementById('mi-embed');if(!fr){fr=document.createElement('iframe');fr.id='mi-embed';fr.title='Gestão de Usuários';fr.src='/api/admin/ui';document.documentElement.appendChild(fr)}var L=sbRight();fr.style.cssText='position:fixed;top:0;left:'+L+'px;width:calc(100vw - '+L+'px);height:100vh;border:0;background:#FBF9F8;z-index:2147483600;display:block';highlight(true);if(push&&location.pathname!==URLP){try{history.pushState({mi:1},'',URLP)}catch(e){}}}
function hideU(){var fr=document.getElementById('mi-embed');if(fr)fr.style.display='none';highlight(false)}
function inject(){try{if(document.getElementById('mi-usuarios'))return;var ref=document.querySelector('a[href="/admin-core-sys/marketing"]')||document.querySelector('a[href^="/admin-core-sys/"]:not([href="/admin-core-sys"])');if(!ref)return;var c=ref.cloneNode(true);c.id='mi-usuarios';c.setAttribute('href',URLP);c.style.cursor='pointer';var wk=document.createTreeWalker(c,NodeFilter.SHOW_TEXT);var t;while(t=wk.nextNode()){if(t.nodeValue&&t.nodeValue.trim()){t.nodeValue='Usuários';break}}var sv=c.querySelector('svg');if(sv)sv.innerHTML='<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>';ref.parentNode.insertBefore(c,ref.nextSibling)}catch(e){}}
document.addEventListener('click',function(e){if(!e.target||!e.target.closest)return;if(e.target.closest('#mi-usuarios')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();showU(true);return}var other=e.target.closest('a[href^="/admin-core-sys"]');if(other&&other.id!=='mi-usuarios'){hideU();var href=other.getAttribute('href');if(href&&location.pathname===URLP)setTimeout(function(){if(location.pathname===URLP){try{history.replaceState({},'',href)}catch(e){}}},10)}},true);
window.addEventListener('popstate',function(){if(location.pathname===URLP)showU(false);else hideU()});
function boot(){inject();if(location.pathname===URLP)showU(false);try{var mo=new MutationObserver(function(){if(!document.getElementById('mi-usuarios'))inject()});mo.observe(document.body,{childList:true,subtree:true})}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();</script>`;
