// Injetado no <head> do /admin-core-sys: adiciona itens no menu lateral (Usuários,
// Comportamento) clonando o item Marketing, e mostra cada tela INLINE na área de conteúdo
// (como as seções nativas). Clicar muda a URL (/admin-core-sys/<x>); clicar em outra seção fecha.
// JS sem backticks/${}.
export const MENU_INJECT = `<script>(function(){
var ITEMS=[
 {id:'mi-usuarios',label:'Usuários',url:'/admin-core-sys/users',src:'/api/admin/ui',icon:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>'},
 {id:'mi-analytics',label:'Comportamento',url:'/admin-core-sys/analytics',src:'/api/admin/analytics',icon:'<path d="M3 3v18h18"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/>'}
];
function sbRight(){try{var a=document.querySelector('a[href="/admin-core-sys"]')||document.querySelector('a[href^="/admin-core-sys"]');if(!a)return 240;var sb=a;while(sb.parentElement&&sb.parentElement.querySelectorAll('a[href^="/admin-core-sys"]').length>=3)sb=sb.parentElement;var r=Math.round(sb.getBoundingClientRect().right);return (r>80&&r<520)?r:240}catch(e){return 240}}
function itemByPath(p){for(var i=0;i<ITEMS.length;i++){if(ITEMS[i].url===p)return ITEMS[i]}return null}
function highlight(active){ITEMS.forEach(function(it){var el=document.getElementById(it.id);if(!el)return;if(active&&it.id===active.id){el.style.background='oklch(0.969 0.015 12.422)';el.style.color='oklch(0.514 0.222 16.935)';el.style.borderRadius='12px'}else{el.style.background='';el.style.color='';el.style.borderRadius=''}})}
function showU(item,push){var fr=document.getElementById('mi-embed');if(!fr){fr=document.createElement('iframe');fr.id='mi-embed';document.documentElement.appendChild(fr)}if(fr.getAttribute('data-src')!==item.src){fr.src=item.src;fr.setAttribute('data-src',item.src)}var L=sbRight();fr.style.cssText='position:fixed;top:0;left:'+L+'px;width:calc(100vw - '+L+'px);height:100vh;border:0;background:#FBF9F8;z-index:2147483600;display:block';highlight(item);if(push&&location.pathname!==item.url){try{history.pushState({mi:1},'',item.url)}catch(e){}}}
function hideAll(){var fr=document.getElementById('mi-embed');if(fr)fr.style.display='none';highlight(null)}
function injectOne(item,ref){var c=ref.cloneNode(true);c.id=item.id;c.setAttribute('href',item.url);c.style.cursor='pointer';var wk=document.createTreeWalker(c,NodeFilter.SHOW_TEXT);var t;while(t=wk.nextNode()){if(t.nodeValue&&t.nodeValue.trim()){t.nodeValue=item.label;break}}var sv=c.querySelector('svg');if(sv)sv.innerHTML=item.icon;ref.parentNode.insertBefore(c,ref.nextSibling);return c}
function inject(){try{var ref=document.querySelector('a[href="/admin-core-sys/marketing"]')||document.querySelector('a[href^="/admin-core-sys/"]:not([href="/admin-core-sys"])');if(!ref)return;var prev=ref;for(var i=0;i<ITEMS.length;i++){var ex=document.getElementById(ITEMS[i].id);if(ex){prev=ex;continue}prev=injectOne(ITEMS[i],prev)}}catch(e){}}
document.addEventListener('click',function(e){if(!e.target||!e.target.closest)return;if(e.target.closest('#mi-logout')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();var go=function(){location.replace('/admin-core-sys?out='+Date.now())};fetch('/api/admin/logout',{method:'POST',credentials:'include'}).then(go).catch(go);return}for(var i=0;i<ITEMS.length;i++){if(e.target.closest('#'+ITEMS[i].id)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();showU(ITEMS[i],true);return}}var other=e.target.closest('a[href^="/admin-core-sys"]');if(other){hideAll();var href=other.getAttribute('href');if(href&&itemByPath(location.pathname))setTimeout(function(){if(itemByPath(location.pathname)){try{history.replaceState({},'',href)}catch(e){}}},10)}},true);
window.addEventListener('popstate',function(){var it=itemByPath(location.pathname);if(it)showU(it,false);else hideAll()});
function fixScroll(){try{var a=document.querySelector('a[href^="/admin-core-sys"]');if(!a)return;var sb=a;while(sb.parentElement&&sb.parentElement.querySelectorAll('a[href^="/admin-core-sys"]').length>=3&&sb.parentElement.getBoundingClientRect().width<520)sb=sb.parentElement;if(!sb||sb.getAttribute('data-mi-scroll'))return;var r=sb.getBoundingClientRect();if(r.height>window.innerHeight+2||sb.scrollHeight>sb.clientHeight+4){sb.style.maxHeight='100vh';sb.style.overflowY='auto';sb.setAttribute('data-mi-scroll','1')}}catch(e){}}
function injectLogout(){try{if(document.getElementById('mi-logout'))return;var a=document.querySelector('a[href="/admin-core-sys/marketing"]');if(!a)return;var sidebar=a.parentElement.parentElement;var footer=sidebar.lastElementChild;if(!footer||footer.querySelector('a[href^="/admin-core-sys"]'))return;var ref=footer.querySelector('a')||footer.querySelector('button');if(!ref)return;var c=ref.cloneNode(true);c.id='mi-logout';c.removeAttribute('href');c.style.cursor='pointer';var wk=document.createTreeWalker(c,NodeFilter.SHOW_TEXT);var t;while(t=wk.nextNode()){if(t.nodeValue&&t.nodeValue.trim()){t.nodeValue='Sair do Painel';break}}footer.style.display='flex';footer.style.flexDirection='column';footer.style.gap='6px';footer.appendChild(c)}catch(e){}}
function boot(){inject();injectLogout();fixScroll();var it=itemByPath(location.pathname);if(it)showU(it,false);try{var mo=new MutationObserver(function(){if(ITEMS.some(function(x){return !document.getElementById(x.id)}))inject();if(!document.getElementById('mi-logout'))injectLogout();fixScroll()});mo.observe(document.body,{childList:true,subtree:true})}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();</script>`;
